### ISSUE TITLE
clpallette broken

### ISSUE THREAD

**Issue by wijjy** [andrewheiss/colourlovers#14]
Something is wrong.  I don't know if it is the API or your code.  Code for `clpallete `and `clpalettes ` returns error codes.

Thank you.
 
```
palette1 <- clpalette('113451')
Opening and ending tag mismatch: input line 114 and form
Opening and ending tag mismatch: input line 114 and div
Opening and ending tag mismatch: input line 114 and div
Opening and ending tag mismatch: form line 114 and div
Entity 'bull' not defined
Entity 'bull' not defined
Opening and ending tag mismatch: div line 114 and body
Opening and ending tag mismatch: div line 114 and html
EndTag: '</' not found
Error: 1: Opening and ending tag mismatch: input line 114 and form
2: Opening and ending tag mismatch: input line 114 and div
3: Opening and ending tag mismatch: input line 114 and div
4: Opening and ending tag mismatch: form line 114 and div
5: Entity 'bull' not defined
6: Entity 'bull' not defined
7: Opening and ending tag mismatch: div line 114 and body
8: Opening and ending tag mismatch: div line 114 and html
9: EndTag: '</' not found
```

**Comment by donny-son** [comment]
I think there was a change in the API.

**Comment by MartinMSPedersen** [comment]
The code fails on this line:
```r
        p <- xmlParse(response, options = XML::NOCDATA)
```
in R/clQuery.R

**Comment by MartinMSPedersen** [comment]
It is colourlovers api that ask for a captcha
https://www.colourlovers.com/forums/2,5,343389/api_broken._asking_for_captcha...

**Comment by MartinMSPedersen** [comment]
I have solved this problem and created a PR!
Huray!
https://github.com/andrewheiss/colourlovers/pull/17

**Comment by MartinMSPedersen** [comment]
Now it works. Until the PR is accepted, you can use my version:
```r
devtools::install_github("martinmspedersen/colourlovers")
library(colourlovers)
clpalette('1')
```

> Palette ID:      1 
> Title:           metro 
> Created by user: COLOURlover 
> Date created:    2004-12-27 14:53:30 
> Views:           114754 
> Votes:           1432 
> Comments:        47 
> Hearts:          5 
> Rank:            55 
> URL:             http://www.colourlovers.com/palette/1/metro 
> Image URL:       
> Colors:          #515151, #FFFFFF, #00B4FF, #EEEEEE 
>

**Comment by andrewheiss** [comment]
Thanks for figuring this out!

**Comment by MartinMSPedersen** [comment]
New problem and a fix:
https://github.com/andrewheiss/colourlovers/pull/20/commits/49f405c71d032d02eb45e50ed4570067c753493b
