### ISSUE TITLE
Seeking new maintainer

### ISSUE THREAD

**Issue by leeper** [andrewheiss/colourlovers#7]
This package is not being actively maintained. If you're interested in contributing or taking over, please express your interest here.

**Comment by leeper** [comment]
Need to fix errors to get on CRAN:

```
See 
https://cran.r-project.org/web/checks/check_results_colourlovers.html . 
Recent check runs are gettting 403 errors.

This looks like a permanent change, but there is also the CRAN policy

'Packages which use Internet resources should fail gracefully with an 
informative message if the resource is not available (and not give a 
check warning nor error).'

You need such protection in clpng, and for clpattern it would better be 
in  the function than in the examples.

Please correct ASAP and before Feb 18 to safely retain to CRAN.
```

**Comment by SamanthaToet** [comment]
Taking a stab at this now!

**Comment by samprohaska** [comment]
I'd love to help out!

**Comment by leeper** [comment]
@samprohaska If you want to take it over, send a PR that changes the maintainer field in DESCRIPTION and fixes whatever R CMD check errors there are. I can then add you as an editor and you can transfer the repo to your own account.

**Comment by andrewheiss** [comment]
This should be fixed in https://github.com/andrewheiss/colourlovers

**Comment by andrewheiss** [comment]
Oof, *this* = the R CMD check errors. I'd be happy to take this on as maintainer too, but I haven't updated that information in my fork yet.

**Comment by leeper** [comment]
Thanks, @andrewheiss! Glad you’re able to take the lead on this. Andrew will be taking over as maintainer - if anyone else wants to contribute, please reach out to him.
